language: generic 

sudo: required
services:
  - docker

before_install:
  - docker build -t zihan42/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true zihan42/react-test npm test

after_success:
  - docker build -t zihan42/multi-client ./client
  - docker build -t zihan42/multi-nginx ./nginx
  - docker build -t zihan42/multi-server ./server
  - docker build -t zihan42/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push zihan42/multi-client
  - docker push zihan42/multi-nginx
  - docker push zihan42/multi-server
  - docker push zihan42/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-us-west-1-024385552793
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY